import 'package:flutter/material.dart';
import '../constants/app_colors.dart';
import '../theme/app_theme.dart';
import '../services/platform_operations_service.dart';

class SecuritySettingsScreen extends StatefulWidget { const SecuritySettingsScreen({super.key}); @override State<SecuritySettingsScreen> createState()=>_SecuritySettingsScreenState(); }
class _SecuritySettingsScreenState extends State<SecuritySettingsScreen>{ final api=PlatformOperationsService(); bool loading=true,saving=false,loginAlerts=true,newDeviceAlerts=true,requestFilter=true,searchEmail=false,searchPhone=false; List<Map<String,dynamic>> sessions=[];
  @override void initState(){super.initState(); _load();}
  Future<void> _load() async { try { final s=await api.securitySettings(); sessions=await api.sessions(); loginAlerts=s['login_alerts']??true;newDeviceAlerts=s['new_device_alerts']??true;requestFilter=s['message_request_filter']??true;searchEmail=s['allow_search_by_email']??false;searchPhone=s['allow_search_by_phone']??false; } catch(_){ } if(mounted)setState(()=>loading=false); }
  Future<void> _save() async { setState(()=>saving=true); try { await api.updateSecuritySettings({'login_alerts':loginAlerts,'new_device_alerts':newDeviceAlerts,'message_request_filter':requestFilter,'allow_search_by_email':searchEmail,'allow_search_by_phone':searchPhone}); } finally { if(mounted)setState(()=>saving=false); } }
  Widget sw(String t,String sub,bool v,ValueChanged<bool> c)=>SwitchListTile(contentPadding:EdgeInsets.zero,title:Text(t,style:AppTheme.body(14)),subtitle:Text(sub,style:AppTheme.body(11,color:AppColors.sub)),value:v,onChanged:(x){c(x);_save();});
  @override Widget build(BuildContext context){ if(loading)return const Center(child:CircularProgressIndicator()); return Scaffold(appBar:AppBar(title:Text('SECURITY',style:AppTheme.display(22))),body:ListView(padding:const EdgeInsets.all(20),children:[Text('ACCOUNT PROTECTION',style:AppTheme.display(18)),sw('Login alerts','Notify me about account sign-ins',loginAlerts,(v)=>setState(()=>loginAlerts=v)),sw('New device alerts','Warn me when a new device appears',newDeviceAlerts,(v)=>setState(()=>newDeviceAlerts=v)),sw('Message request filter','Filter suspicious unsolicited messages',requestFilter,(v)=>setState(()=>requestFilter=v)),const Divider(),Text('DISCOVERABILITY',style:AppTheme.display(18)),sw('Find me by email','Allow email-based account discovery',searchEmail,(v)=>setState(()=>searchEmail=v)),sw('Find me by phone','Allow phone-based account discovery',searchPhone,(v)=>setState(()=>searchPhone=v)),const Divider(),Text('ACTIVE SESSIONS',style:AppTheme.display(18)),if(sessions.isEmpty)Text('No additional sessions recorded yet.',style:AppTheme.body(12,color:AppColors.sub)),...sessions.map((s)=>ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(Icons.devices,color:AppColors.green),title:Text(s['device_label']??'Device',style:AppTheme.body(14)),subtitle:Text('${s['platform']??'unknown'} • ${s['last_seen_at']??''}',style:AppTheme.body(11,color:AppColors.sub)),trailing:s['revoked_at']==null?TextButton(onPressed:()=>api.revokeSession(s['id']).then((_){_load();}),child:const Text('Revoke')):const Text('Revoked')),),if(saving)const LinearProgressIndicator(),const SizedBox(height:20),Text('Security events and recovery codes are protected server-side. Never share recovery codes with another person.',style:AppTheme.body(11,color:AppColors.sub))])); }
}
