(() => {
  const C = window.FUSKAMO_CONFIG || {};
  const state = { supabase: null, user: null, profile: null, current: 'home', cache: {posts:[],players:[],groups:[],stories:[]} };
  const $ = id => document.getElementById(id);
  const esc = s => String(s ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const toast = (m, error=false) => { const e=$('toast'); e.textContent=m; e.className='toast show'+(error?' error':''); setTimeout(()=>e.className='toast',2600); };
  function backend(path, opts={}) { const base=(C.BACKEND_BASE_URL||'').replace(/\/$/,''); if(!base) return Promise.reject(new Error('Backend URL is not configured')); const headers={'Content-Type':'application/json',...(C.BACKEND_API_KEY?{'X-API-Key':C.BACKEND_API_KEY}:{}),...(opts.headers||{})}; return fetch(base+path,{...opts,headers}).then(async r=>{const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||data.message||`Request failed (${r.status})`);return data;}); }
  async function init() {
    if(C.SUPABASE_URL && C.SUPABASE_ANON_KEY) { state.supabase = window.supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY); const {data}=await state.supabase.auth.getUser(); state.user=data.user; state.supabase.auth.onAuthStateChange((_e,s)=>{state.user=s?.user||null;renderAccount();refresh();}); }
    renderAccount(); bind(); refresh();
  }
  function bind() {
    document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));
    $('authBtn').onclick=()=>state.user?signOut():$('authModal').classList.add('show'); $('closeAuth').onclick=()=>$('authModal').classList.remove('show'); $('signIn').onclick=signIn; $('signUp').onclick=signUp;
    $('postBtn').onclick=createPost; $('createGroupBtn').onclick=()=>$('groupModal').classList.add('show'); $('closeGroup').onclick=()=>$('groupModal').classList.remove('show'); $('saveGroup').onclick=createGroup;
    $('closeNote').onclick=()=>$('noteModal').classList.remove('show'); $('saveNote').onclick=postNote;
    $('globalSearch').onkeydown=e=>{if(e.key==='Enter'){show('search');$('searchInput').value=e.target.value;runSearch();}}; $('searchInput').oninput=runSearch;
    $('feed').addEventListener('click',onFeedAction); $('storiesList').addEventListener('click',onStoryClick); $('homeStories').addEventListener('click',onStoryClick);
  }
  function renderAccount(){ $('accountText').textContent=state.user?(state.user.email||'Signed in'):'Not signed in'; $('authBtn').textContent=state.user?'Sign out':'Sign in'; if(state.user) loadProfile(); }
  function show(name){state.current=name;document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===name));document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('title').textContent=name[0].toUpperCase()+name.slice(1); if(name==='search')runSearch(); if(name==='profile')loadProfile();}
  async function signIn(){ if(!state.supabase)return toast('Add Supabase settings first',true); try{const {error}=await state.supabase.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)throw error;$('authModal').classList.remove('show');toast('Signed in');}catch(e){$('authError').textContent=e.message;}}
  async function signUp(){ if(!state.supabase)return toast('Add Supabase settings first',true); try{const {error}=await state.supabase.auth.signUp({email:$('email').value.trim(),password:$('password').value});if(error)throw error;toast('Account created. Check your email if confirmation is enabled.');}catch(e){$('authError').textContent=e.message;}}
  async function signOut(){await state.supabase?.auth.signOut();toast('Signed out');}
  async function loadProfile(){ if(!state.supabase||!state.user)return; try{let q=await state.supabase.from('profiles').select('*').eq('user_id',state.user.id).maybeSingle();state.profile=q.data||{username:state.user.email?.split('@')[0]};$('profileCard').innerHTML=`<div class="post-head"><div class="avatar">${esc((state.profile.username||'U')[0].toUpperCase())}</div><div><h2 style="margin:0">@${esc(state.profile.username||'user')}</h2><div class="muted">${esc(state.profile.display_name||state.user.email||'FUSKAMO member')}</div></div></div><p class="muted">Your identity, trust and achievements are separate from paid promotion.</p>`;}catch(e){$('profileCard').innerHTML='<div class="muted">Profile schema is not connected yet.</div>';}}
  async function refresh(){await Promise.all([loadPosts(),loadPlayers(),loadGroups(),loadScoreboard(),loadStories(),loadMessages()]);renderSuggestions();}
  async function loadPosts(){if(!state.supabase)return renderDemoPosts();try{const {data,error}=await state.supabase.from('social_posts').select('*').eq('visibility','public').eq('status','published').order('created_at',{ascending:false}).limit(20);if(error)throw error;const posts=data||[];const ids=[...new Set(posts.map(p=>p.author_id).filter(Boolean))];let authors={};if(ids.length){const {data:profs}=await state.supabase.from('profiles').select('user_id,username,display_name,avatar_url').in('user_id',ids);(profs||[]).forEach(p=>authors[p.user_id]=p);}
      let liked=new Set(),reposted=new Set();
      if(state.user&&posts.length){const postIds=posts.map(p=>p.id);const [lk,rp]=await Promise.all([state.supabase.from('social_post_likes').select('post_id').eq('user_id',state.user.id).in('post_id',postIds),state.supabase.from('social_reposts').select('post_id').eq('user_id',state.user.id).in('post_id',postIds)]);(lk.data||[]).forEach(r=>liked.add(r.post_id));(rp.data||[]).forEach(r=>reposted.add(r.post_id));}
      state.cache.posts=posts.map(p=>({...p,author_username:authors[p.author_id]?.username,author_name:authors[p.author_id]?.display_name,liked:liked.has(p.id),reposted:reposted.has(p.id)}));renderPosts();}catch(e){renderDemoPosts();}}
  function renderDemoPosts(){state.cache.posts=[{id:'demo-1',body:'Welcome to FUSKAMO — discover football talent, clubs, scouts and coaches.',created_at:new Date().toISOString(),author_username:'fuskamo'}];renderPosts();}
  function renderPosts(){ $('feed').innerHTML=state.cache.posts.length?state.cache.posts.map(p=>`<article class="card" data-post="${esc(p.id)}"><div class="post-head"><div class="avatar">${esc((p.author_username||p.username||'F')[0].toUpperCase())}</div><div><b>@${esc(p.author_username||p.username||'member')}</b><div class="muted">${new Date(p.created_at||Date.now()).toLocaleString()}</div></div></div><div class="post-body">${esc(p.body||p.content||'')}</div><div class="actions">
    <button class="action${p.liked?' liked':''}" data-action="like" data-id="${esc(p.id)}">${p.liked?'♥':'♡'} Like${p.like_count?` · ${p.like_count}`:''}</button>
    <button class="action" data-action="comment" data-id="${esc(p.id)}">💬 Comment${p.comment_count?` · ${p.comment_count}`:''}</button>
    <button class="action${p.reposted?' reposted':''}" data-action="repost" data-id="${esc(p.id)}">⟲ Repost${p.repost_count?` · ${p.repost_count}`:''}</button>
    <button class="action" data-action="share" data-id="${esc(p.id)}">↗ Share</button>
    </div></article>`).join(''):'<div class="empty">No posts yet.</div>';}
  function onFeedAction(e){const btn=e.target.closest('button[data-action]');if(!btn)return;const id=btn.dataset.id;if(btn.dataset.action==='like')toggleLike(id);else if(btn.dataset.action==='repost')toggleRepost(id);else if(btn.dataset.action==='share')sharePost(id);else if(btn.dataset.action==='comment')toast('Comments open inside the FUSKAMO mobile app for now.');}
  async function toggleLike(postId){if(!state.user||!state.supabase)return toast('Sign in to like posts',true);const post=state.cache.posts.find(p=>p.id===postId);if(!post)return;try{const {data,error}=await state.supabase.rpc('toggle_post_like',{p_post:postId});if(error)throw error;post.liked=!!data;post.like_count=(post.like_count||0)+(post.liked?1:-1);renderPosts();}catch(e){toast(e.message,true);}}
  async function toggleRepost(postId){if(!state.user||!state.supabase)return toast('Sign in to repost',true);const post=state.cache.posts.find(p=>p.id===postId);if(!post)return;try{if(post.reposted){const {error}=await state.supabase.from('social_reposts').delete().eq('post_id',postId).eq('user_id',state.user.id);if(error)throw error;post.reposted=false;}else{const {error}=await state.supabase.from('social_reposts').insert({post_id:postId,user_id:state.user.id});if(error)throw error;post.reposted=true;toast('Reposted to your followers');}await state.supabase.rpc('refresh_social_post_counts',{p_post:postId});post.repost_count=(post.repost_count||0)+(post.reposted?1:-1);renderPosts();}catch(e){toast(e.message,true);}}
  async function sharePost(postId){const url=`${location.origin}${location.pathname}#/post/${postId}`;try{if(navigator.share){await navigator.share({title:'FUSKAMO',text:'Check this out on FUSKAMO',url});}else{await navigator.clipboard.writeText(url);toast('Link copied');}}catch(e){/* user cancelled share sheet */}}
  async function createPost(){if(!state.user||!state.supabase)return toast('Sign in to post',true);const body=$('postText').value.trim();if(!body)return;if(body.length>5000)return toast('Post is too long',true);const {error}=await state.supabase.from('social_posts').insert({author_id:state.user.id,body});if(error){toast(error.message,true);return}$('postText').value='';toast('Posted');loadPosts();}
  async function loadPlayers(){if(!state.supabase){renderPlayers([]);return}try{const {data,error}=await state.supabase.from('players').select('*').eq('status','approved').order('featured_until',{ascending:false}).limit(24);if(error)throw error;state.cache.players=data||[];renderPlayers(state.cache.players);}catch(e){renderPlayers([]);}}
  function renderPlayers(items){$('discoverList').innerHTML=items.length?items.map(p=>`<div class="person"><div class="avatar">${esc((p.name||p.username||'P')[0].toUpperCase())}</div><div class="info"><b>${esc(p.name||p.username||'Player')}</b><div class="muted">${esc(p.position||'Player')} • ${esc(p.country||'Football')}</div></div><span class="pill">PLAYER</span></div>`).join(''):'<div class="empty">Connect Supabase to load approved players.</div>';}
  async function loadGroups(){
    if(!state.supabase)return renderGroups([],[]);
    try{
      let mine=[];
      if(state.user){const {data,error}=await state.supabase.from('group_members').select('role,groups(*)').eq('user_id',state.user.id);if(error)throw error;mine=(data||[]).filter(r=>r.groups).map(r=>({...r.groups,myRole:r.role}));}
      const myIds=new Set(mine.map(g=>g.id));
      const {data:pub,error:e2}=await state.supabase.from('groups').select('*').eq('privacy','public').order('member_count',{ascending:false}).limit(20);
      if(e2)throw e2;
      const discover=(pub||[]).filter(g=>!myIds.has(g.id));
      state.cache.groups=[...mine,...discover]; renderGroups(mine,discover);
    }catch(e){renderGroups([],[]);}
  }
  function groupRow(g){const badge=g.myRole==='owner'?'<span class="badge badge-owner">OWNER</span>':g.myRole==='host'?'<span class="badge badge-host">HOST</span>':'';const verified=g.verified?'<span class="badge badge-verified">✓</span>':'';const unread=g.last_activity_at&&(Date.now()-new Date(g.last_activity_at).getTime()<86400000)?`<span class="unread">${g.message_count>99?'99+':'●'}</span>`:'';return `<div class="group" data-action="open-group" data-id="${esc(g.id)}"><div class="avatar">${esc((g.name||'G')[0].toUpperCase())}</div><div class="info"><b>${esc(g.name||'Group')}${badge}${verified}</b><div class="muted">${esc(g.member_count||0)} members${g.privacy==='private'?' · private':''} · ${esc(g.description||'Football community')}</div></div>${unread}<button class="btn" data-action="open-group" data-id="${esc(g.id)}">${g.myRole?'Open':'View'}</button></div>`;}
  function renderGroups(mine,discover){
    let html='';
    if(mine.length)html+=`<div class="grouphead">My groups</div>${mine.map(groupRow).join('')}`;
    html+=`<div class="grouphead">Discover public groups</div>`+(discover.length?discover.map(groupRow).join(''):'<div class="empty">No public groups yet.</div>');
    if(!mine.length&&!discover.length)html='<div class="empty">No groups loaded yet. Create one when authenticated.</div>';
    $('groupsList').innerHTML=html;
    $('groupsList').onclick=e=>{const el=e.target.closest('[data-action="open-group"]');if(!el)return;const g=state.cache.groups.find(x=>x.id===el.dataset.id);if(g)toast(`@${g.name} — ${g.member_count||0} members. Full group chat opens in the FUSKAMO mobile app for now.`);};
  }
  async function createGroup(){if(!state.user||!state.supabase)return toast('Sign in to create groups',true);const name=$('groupName').value.trim();const slug=$('groupSlug').value.trim().toLowerCase();const rules=$('groupRules').value.trim();if(!name||!slug)return toast('Name and username-style slug are required',true);try{const {data,error}=await state.supabase.from('groups').insert({name,slug,rules,owner_id:state.user.id,privacy:'private'}).select().single();if(error)throw error;$('groupModal').classList.remove('show');toast('Private group created');loadGroups();}catch(e){$('groupError').textContent=e.message;}}
  async function loadStories(){
    if(!state.supabase){renderStories([]);return;}
    try{
      const {data,error}=await state.supabase.from('social_stories').select('*').eq('status','published').gt('expires_at',new Date().toISOString()).order('created_at',{ascending:false}).limit(40);
      if(error)throw error;
      const stories=data||[]; const ids=[...new Set(stories.map(s=>s.author_id))];
      let authors={}; if(ids.length){const {data:profs}=await state.supabase.from('profiles').select('user_id,username,display_name,avatar_url').in('user_id',ids);(profs||[]).forEach(p=>authors[p.user_id]=p);}
      const byAuthor={}; stories.forEach(s=>{if(!byAuthor[s.author_id])byAuthor[s.author_id]=[];byAuthor[s.author_id].push(s);});
      state.cache.stories=Object.entries(byAuthor).map(([authorId,list])=>({authorId,latest:list[0],count:list.length,author:authors[authorId]}));
      renderStories(state.cache.stories);
    }catch(e){renderStories([]);}
  }
  function renderStories(items){
    const mine=state.user&&items.find(x=>x.authorId===state.user.id);
    const selfHtml=state.user?`<div class="story self" data-action="add-note"><div class="note-bubble">${mine?esc(mine.latest.media_type==='note'?mine.latest.caption:'View'):'Note…'}</div><div class="avatar">${esc((state.profile?.username||'Y')[0].toUpperCase())}</div><small class="muted">Your note</small></div>`:'';
    const others=items.filter(x=>!state.user||x.authorId!==state.user.id).map((x,i)=>{const idx=state.cache.stories.indexOf(x);const name=x.author?.username||'member';const note=x.latest.media_type==='note'?x.latest.caption:'';return `<div class="story" data-action="view-story" data-index="${idx}"><div class="note-bubble">${note?esc(note):(x.count>1?`${x.count} updates`:'Story')}</div><div class="avatar">${esc(name[0].toUpperCase())}</div><small class="muted">@${esc(name)}</small></div>`;}).join('');
    const html=selfHtml+(others||(state.user?'':'<div class="story"><div class="avatar">F</div><small class="muted">Sign in for notes</small></div>'));
    $('storiesList').innerHTML=html||'<div class="empty" style="padding:8px">No active stories or notes yet.</div>';
    $('homeStories').innerHTML=`<div class="card"><div class="storyrow">${html}</div></div>`;
  }
  function onStoryClick(e){const el=e.target.closest('[data-action]');if(!el)return;if(el.dataset.action==='add-note'){$('noteText').value='';$('noteError').textContent='';$('noteModal').classList.add('show');}else if(el.dataset.action==='view-story'){const s=state.cache.stories[+el.dataset.index];if(!s)return;const name=s.author?.username||'member';if(s.latest.media_type==='note')toast(`@${name}: ${s.latest.caption}`);else toast(`@${name} posted a story — full media playback is coming to the web app soon.`);}}
  async function postNote(){if(!state.user||!state.supabase)return toast('Sign in to share a note',true);const caption=$('noteText').value.trim();if(!caption)return toast('Write something first',true);if(caption.length>60)return toast('Notes are capped at 60 characters',true);try{const {error}=await state.supabase.from('social_stories').insert({author_id:state.user.id,media_type:'note',caption,visibility:'followers',expires_at:new Date(Date.now()+2*3600*1000).toISOString()});if(error)throw error;$('noteModal').classList.remove('show');toast('Note shared — visible for 2 hours');loadStories();}catch(e){$('noteError').textContent=e.message;}}
  async function loadMessages(){const e=$('messagesList');e.innerHTML=['Message requests','Recent conversations','Pinned conversations'].map((x,i)=>`<div class="person"><div class="avatar">${['↗','✉','📌'][i]}</div><div class="info"><b>${x}</b><div class="muted">Available when messaging backend is connected.</div></div></div>`).join('');}
  async function loadScoreboard(){const e=$('scoreList');const players=state.cache.players.slice(0,10);e.innerHTML=players.length ? players.map((p,i)=>`<div class="person"><b style="width:26px">#${i+1}</b><div class="avatar">${esc((p.name||'P')[0])}</div><div class="info"><b>${esc(p.name||'Player')}</b><div class="muted">Trust-aware ranking • meaningful activity</div></div><span class="goldpill pill">${1000-i*37}</span></div>`).join('') : Array.from({length:5},(_,i)=>`<div class="person"><b>#${i+1}</b><div class="info"><b>FUSKAMO ${['Player','Scout','Club','Coach','Rising Star'][i]}</b><div class="muted">Scoreboard preview</div></div><span class="goldpill pill">${1000-i*51}</span></div>`).join('');}
  function renderSuggestions(){ $('suggested').innerHTML=['Verified clubs','Rising players','Active scouts'].map((x,i)=>`<div class="person"><div class="avatar">${['C','P','S'][i]}</div><div class="info"><b>${x}</b><div class="muted">Trust-first discovery</div></div></div>`).join('');}
  async function runSearch(){const q=$('searchInput').value.trim().toLowerCase();if(!q){$('searchResults').innerHTML='<div class="empty">Search the football network.</div>';return}const local=[...state.cache.players.map(p=>({type:'Player',name:p.name||p.username,meta:p.position||''})),...state.cache.groups.map(g=>({type:'Group',name:g.name,meta:g.description||''}))].filter(x=>(x.name||'').toLowerCase().includes(q)||(x.meta||'').toLowerCase().includes(q));$('searchResults').innerHTML=local.length?local.map(x=>`<div class="person"><div class="avatar">${esc((x.name||'?')[0].toUpperCase())}</div><div class="info"><b>${esc(x.name||'Result')}</b><div class="muted">${esc(x.type)} • ${esc(x.meta)}</div></div></div>`).join(''):'<div class="empty">No local results. Full universal search requires the configured backend.</div>';try{const r=await backend('/api/search?q='+encodeURIComponent(q));if(r?.results?.length){$('searchResults').insertAdjacentHTML('afterbegin',r.results.map(x=>`<div class="person"><div class="avatar">${esc((x.name||'?')[0])}</div><div class="info"><b>${esc(x.name)}</b><div class="muted">${esc(x.type||'Result')}</div></div></div>`).join(''))}}catch(_){} }
  init();
})();
