import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../constants/app_colors.dart';
import '../services/supabase_service.dart';
import '../repositories/messaging_repository.dart';
import '../repositories/badge_repository.dart';
import '../theme/app_theme.dart';

class EditProfileScreen extends StatefulWidget {
  const EditProfileScreen({super.key});
  @override State<EditProfileScreen> createState()=>_EditProfileScreenState();
}
class _EditProfileScreenState extends State<EditProfileScreen> {
  late final TextEditingController _name,_username,_bio,_website,_instagram,_x,_tiktok,_snapchat,_bluesky,_avatar,_identityClaim;
  bool _saving=false;
  String _role='player';
  User get _user=>SupabaseService.client.auth.currentUser!;
  @override void initState(){super.initState();final m=_user.userMetadata??{};String v(String k)=>m[k]?.toString()??'';_name=TextEditingController(text:v('display_name'));_username=TextEditingController(text:v('username'));_bio=TextEditingController(text:v('bio'));_website=TextEditingController(text:v('website'));_instagram=TextEditingController(text:v('instagram'));_x=TextEditingController(text:v('x'));_tiktok=TextEditingController(text:v('tiktok'));_snapchat=TextEditingController(text:v('snapchat'));_bluesky=TextEditingController(text:v('bluesky'));_avatar=TextEditingController(text:v('avatar_url'));_identityClaim=TextEditingController(text:v('identity_claim'));_role=v('role').isEmpty?'player':v('role');}
  @override void dispose(){for(final c in [_name,_username,_bio,_website,_instagram,_x,_tiktok,_snapchat,_bluesky,_avatar,_identityClaim])c.dispose();super.dispose();}
  Future<void> _save() async {setState(()=>_saving=true);try{await SupabaseService.client.auth.updateUser(UserAttributes(data:{'display_name':_name.text.trim(),'username':_username.text.trim().replaceFirst('@','').toLowerCase(),'bio':_bio.text.trim(),'website':_website.text.trim(),'instagram':_instagram.text.trim().replaceFirst('@',''),'x':_x.text.trim().replaceFirst('@',''),'tiktok':_tiktok.text.trim().replaceFirst('@',''),'snapchat':_snapchat.text.trim().replaceFirst('@',''),'bluesky':_bluesky.text.trim().replaceFirst('@',''),'avatar_url':_avatar.text.trim()}));
      await MessagingRepository().ensureMyProfile(displayName:_name.text.trim(),username:_username.text.trim().replaceFirst('@','').toLowerCase(),bio:_bio.text.trim(),avatarUrl:_avatar.text.trim(),website:_website.text.trim(),instagram:_instagram.text.trim().replaceFirst('@',''),xHandle:_x.text.trim().replaceFirst('@',''),tiktok:_tiktok.text.trim().replaceFirst('@',''),snapchat:_snapchat.text.trim().replaceFirst('@',''),bluesky:_bluesky.text.trim().replaceFirst('@',''),role:_role);
      await BadgeRepository().setIdentityClaim(_identityClaim.text.trim().isEmpty ? null : _identityClaim.text.trim());
      if(mounted){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Profile updated.')));Navigator.pop(context,true);}}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Could not update profile: $e')));}finally{if(mounted)setState(()=>_saving=false);}}
  Widget _field(String label,TextEditingController c,{String? prefix,int maxLines=1,List<TextInputFormatter>? inputFormatters,String? helper})=>Padding(padding:const EdgeInsets.only(bottom:14),child:TextField(controller:c,maxLines:maxLines,decoration:InputDecoration(labelText:label,prefixText:prefix,helperText:helper),inputFormatters: inputFormatters));
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text('EDIT PROFILE',style:AppTheme.display(22)),actions:[TextButton(onPressed:_saving?null:_save,child:const Text('SAVE'))]),body:ListView(padding:const EdgeInsets.all(20),children:[Center(child:Stack(children:[CircleAvatar(radius:58,backgroundImage:_avatar.text.trim().isNotEmpty?NetworkImage(_avatar.text.trim()):null,backgroundColor:AppColors.card,child:_avatar.text.trim().isEmpty?const Icon(Icons.person,size:54,color:AppColors.sub):null),Positioned(right:0,bottom:0,child:IconButton(onPressed:()=>setState((){}),style:IconButton.styleFrom(backgroundColor:AppColors.surface),icon:const Icon(Icons.refresh)))])),const SizedBox(height:26),_field('DISPLAY NAME',_name),_field('USERNAME',_username,prefix:'@ ',inputFormatters: [], helper:'3–20 chars: lowercase letters, numbers and underscores. Starts with a letter. Changes are limited to once every 30 days.'),_field('BIO',_bio,maxLines:4),_field('PROFILE IMAGE URL',_avatar),_field('PERSON / CLUB YOU ARE REFERENCING (OPTIONAL)',_identityClaim),Text('If you reference a club or public person without verification, FUSKAMO will display a clear non-affiliation notice. Do not imply official affiliation unless you have evidence.',style:AppTheme.body(11,color:AppColors.sub)),const SizedBox(height:8),Text('ACCOUNT TYPE',style:AppTheme.display(18)),const SizedBox(height:8),DropdownButtonFormField<String>(value:_role,decoration:const InputDecoration(labelText:'Role'),items:const [DropdownMenuItem(value:'player',child:Text('Player')),DropdownMenuItem(value:'scout',child:Text('Scout')),DropdownMenuItem(value:'coach',child:Text('Coach')),DropdownMenuItem(value:'club',child:Text('Club')),DropdownMenuItem(value:'fan',child:Text('Fan'))],onChanged:(v){if(v!=null)setState(()=>_role=v);}),const SizedBox(height:18),Text('LINKS',style:AppTheme.display(18)),const SizedBox(height:12),_field('WEB LINK',_website),_field('INSTAGRAM',_instagram,prefix:'@ '),_field('X (FORMERLY TWITTER)',_x,prefix:'@ '),_field('TIKTOK',_tiktok,prefix:'@ '),_field('SNAPCHAT',_snapchat,prefix:'@ '),_field('BLUESKY',_bluesky,prefix:'@ '),const SizedBox(height:10),SizedBox(height:48,child:ElevatedButton(onPressed:_saving?null:_save,child:_saving?const CircularProgressIndicator(strokeWidth:2,color:AppColors.black):const Text('SAVE CHANGES')))]));
}
