(() => {
  const C = window.FUSKAMO_CONFIG || {};
  const state = { supabase: null, user: null, profile: null, current: 'home', cache: {posts:[],players:[],groups:[]} };
  const $ = id => document.getElementById(id);
  const esc = s => String(s ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const toast = (m, error=false) => { const e=$('toast'); e.textContent=m; e.className='toast show'+(error?' error':''); setTimeout(()=>e.className='toast',2600); };
  function backend(path, opts={}) { const base=(C.BACKEND_BASE_URL||'').replace(/\/$/,''); if(!base) return Promise.reject(new Error('Backend URL is not configured')); const headers={'Content-Type':'application/json',...(C.BACKEND_API_KEY?{'X-API-Key':C.BACKEND_API_KEY}:{}),...(opts.headers||{})}; return fetch(base+path,{...opts,headers}).then(async r=>{const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||data.message||`Request failed (${r.status})`);return data;}); }
  async function init() {
    if(C.SUPABASE_URL && C.SUPABASE_ANON_KEY) { state.supabase = window.supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY); const {data}=await state.supabase.auth.getUser(); state.user=data.user; state.supabase.auth.onAuthStateChange((_e,s)=>{state.user=s?.user||null;renderAccount();refresh();}); }
    renderAccount(); bind(); refresh();
  }
  function bind() {
    document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));
    $('authBtn').onclick=()=>state.user?signOut():$('authModal').classList.add('show'); $('closeAuth').onclick=()=>$('authModal').classList.remove('show'); $('signIn').onclick=signIn; $('signUp').onclick=signUp;
    $('postBtn').onclick=createPost; $('createGroupBtn').onclick=()=>$('groupModal').classList.add('show'); $('closeGroup').onclick=()=>$('groupModal').classList.remove('show'); $('saveGroup').onclick=createGroup;
    $('globalSearch').onkeydown=e=>{if(e.key==='Enter'){show('search');$('searchInput').value=e.target.value;runSearch();}}; $('searchInput').oninput=runSearch;
  }
  function renderAccount(){ $('accountText').textContent=state.user?(state.user.email||'Signed in'):'Not signed in'; $('authBtn').textContent=state.user?'Sign out':'Sign in'; if(state.user) loadProfile(); }
  function show(name){state.current=name;document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===name));document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('title').textContent=name[0].toUpperCase()+name.slice(1); if(name==='search')runSearch(); if(name==='profile')loadProfile();}
  async function signIn(){ if(!state.supabase)return toast('Add Supabase settings first',true); try{const {error}=await state.supabase.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)throw error;$('authModal').classList.remove('show');toast('Signed in');}catch(e){$('authError').textContent=e.message;}}
  async function signUp(){ if(!state.supabase)return toast('Add Supabase settings first',true); try{const {error}=await state.supabase.auth.signUp({email:$('email').value.trim(),password:$('password').value});if(error)throw error;toast('Account created. Check your email if confirmation is enabled.');}catch(e){$('authError').textContent=e.message;}}
  async function signOut(){await state.supabase?.auth.signOut();toast('Signed out');}
  async function loadProfile(){ if(!state.supabase||!state.user)return; try{let q=await state.supabase.from('profiles').select('*').eq('id',state.user.id).maybeSingle();state.profile=q.data||{username:state.user.email?.split('@')[0]};$('profileCard').innerHTML=`<div class="post-head"><div class="avatar">${esc((state.profile.username||'U')[0].toUpperCase())}</div><div><h2 style="margin:0">@${esc(state.profile.username||'user')}</h2><div class="muted">${esc(state.profile.full_name||state.user.email||'FUSKAMO member')}</div></div></div><p class="muted">Your identity, trust and achievements are separate from paid promotion.</p>`;}catch(e){$('profileCard').innerHTML='<div class="muted">Profile schema is not connected yet.</div>';}}
  async function refresh(){await Promise.all([loadPosts(),loadPlayers(),loadGroups(),loadScoreboard(),loadStories(),loadMessages()]);renderSuggestions();}
  async function loadPosts(){if(!state.supabase)return renderDemoPosts();try{const {data,error}=await state.supabase.from('posts').select('*').order('created_at',{ascending:false}).limit(20);if(error)throw error;state.cache.posts=data||[];renderPosts();}catch(e){renderDemoPosts();}}
  function renderDemoPosts(){state.cache.posts=[{id:'demo-1',body:'Welcome to FUSKAMO — discover football talent, clubs, scouts and coaches.',created_at:new Date().toISOString(),author_username:'fuskamo'}];renderPosts();}
  function renderPosts(){ $('feed').innerHTML=state.cache.posts.length?state.cache.posts.map(p=>`<article class="card"><div class="post-head"><div class="avatar">${esc((p.author_username||p.username||'F')[0].toUpperCase())}</div><div><b>@${esc(p.author_username||p.username||'member')}</b><div class="muted">${new Date(p.created_at||Date.now()).toLocaleString()}</div></div></div><div class="post-body">${esc(p.body||p.content||'')}</div><div class="actions"><button class="action" data-action="like" data-id="${esc(p.id)}">♡ Like</button><button class="action">💬 Comment</button><button class="action">↗ Share</button><button class="action">☆ Save</button></div></article>`).join(''):'<div class="empty">No posts yet.</div>';}
  async function createPost(){if(!state.user||!state.supabase)return toast('Sign in to post',true);const body=$('postText').value.trim();if(!body)return;if(body.length>5000)return toast('Post is too long',true);const {error}=await state.supabase.from('posts').insert({author_id:state.user.id,body});if(error){toast(error.message,true);return}$('postText').value='';toast('Posted');loadPosts();}
  async function loadPlayers(){if(!state.supabase){renderPlayers([]);return}try{const {data,error}=await state.supabase.from('players').select('*').eq('status','approved').order('featured_until',{ascending:false}).limit(24);if(error)throw error;state.cache.players=data||[];renderPlayers(state.cache.players);}catch(e){renderPlayers([]);}}
  function renderPlayers(items){$('discoverList').innerHTML=items.length?items.map(p=>`<div class="person"><div class="avatar">${esc((p.name||p.username||'P')[0].toUpperCase())}</div><div class="info"><b>${esc(p.name||p.username||'Player')}</b><div class="muted">${esc(p.position||'Player')} • ${esc(p.country||'Football')}</div></div><span class="pill">PLAYER</span></div>`).join(''):'<div class="empty">Connect Supabase to load approved players.</div>';}
  async function loadGroups(){if(!state.supabase)return renderGroups([]);try{const {data,error}=await state.supabase.from('groups').select('*').order('created_at',{ascending:false}).limit(30);if(error)throw error;state.cache.groups=data||[];renderGroups(state.cache.groups);}catch(e){renderGroups([]);}}
  function renderGroups(items){$('groupsList').innerHTML=items.length?items.map(g=>`<div class="group"><div class="avatar">${esc((g.name||'G')[0].toUpperCase())}</div><div class="info"><b>${esc(g.name||'Group')}</b><div class="muted">${esc(g.description||'Football community')}</div></div><span class="pill">${g.privacy==='private'?'PRIVATE':'OPEN'}</span><button class="btn">View</button></div>`).join(''):'<div class="empty">No groups loaded yet. Create one when authenticated.</div>';}
  async function createGroup(){if(!state.user||!state.supabase)return toast('Sign in to create groups',true);const name=$('groupName').value.trim();const slug=$('groupSlug').value.trim().toLowerCase();const rules=$('groupRules').value.trim();if(!name||!slug)return toast('Name and username-style slug are required',true);try{const {data,error}=await state.supabase.from('groups').insert({name,slug,rules,owner_id:state.user.id,privacy:'private'}).select().single();if(error)throw error;$('groupModal').classList.remove('show');toast('Private group created');loadGroups();}catch(e){$('groupError').textContent=e.message;}}
  async function loadStories(){const el=$('storiesList');el.innerHTML=['You','Players','Scouts','Clubs','Coaches'].map((x,i)=>`<div class="story"><div class="avatar">${x[0]}</div><small class="muted">${x}</small></div>`).join('');$('homeStories').innerHTML=`<div class="card"><div class="storyrow">${el.innerHTML}</div></div>`;}
  async function loadMessages(){const e=$('messagesList');e.innerHTML=['Message requests','Recent conversations','Pinned conversations'].map((x,i)=>`<div class="person"><div class="avatar">${['↗','✉','📌'][i]}</div><div class="info"><b>${x}</b><div class="muted">Available when messaging backend is connected.</div></div></div>`).join('');}
  async function loadScoreboard(){const e=$('scoreList');const players=state.cache.players.slice(0,10);e.innerHTML=players.length ? players.map((p,i)=>`<div class="person"><b style="width:26px">#${i+1}</b><div class="avatar">${esc((p.name||'P')[0])}</div><div class="info"><b>${esc(p.name||'Player')}</b><div class="muted">Trust-aware ranking • meaningful activity</div></div><span class="goldpill pill">${1000-i*37}</span></div>`).join('') : Array.from({length:5},(_,i)=>`<div class="person"><b>#${i+1}</b><div class="info"><b>FUSKAMO ${['Player','Scout','Club','Coach','Rising Star'][i]}</b><div class="muted">Scoreboard preview</div></div><span class="goldpill pill">${1000-i*51}</span></div>`).join('');}
  function renderSuggestions(){ $('suggested').innerHTML=['Verified clubs','Rising players','Active scouts'].map((x,i)=>`<div class="person"><div class="avatar">${['C','P','S'][i]}</div><div class="info"><b>${x}</b><div class="muted">Trust-first discovery</div></div></div>`).join('');}
  async function runSearch(){const q=$('searchInput').value.trim().toLowerCase();if(!q){$('searchResults').innerHTML='<div class="empty">Search the football network.</div>';return}const local=[...state.cache.players.map(p=>({type:'Player',name:p.name||p.username,meta:p.position||''})),...state.cache.groups.map(g=>({type:'Group',name:g.name,meta:g.description||''}))].filter(x=>(x.name||'').toLowerCase().includes(q)||(x.meta||'').toLowerCase().includes(q));$('searchResults').innerHTML=local.length?local.map(x=>`<div class="person"><div class="avatar">${esc((x.name||'?')[0].toUpperCase())}</div><div class="info"><b>${esc(x.name||'Result')}</b><div class="muted">${esc(x.type)} • ${esc(x.meta)}</div></div></div>`).join(''):'<div class="empty">No local results. Full universal search requires the configured backend.</div>';try{const r=await backend('/api/search?q='+encodeURIComponent(q));if(r?.results?.length){$('searchResults').insertAdjacentHTML('afterbegin',r.results.map(x=>`<div class="person"><div class="avatar">${esc((x.name||'?')[0])}</div><div class="info"><b>${esc(x.name)}</b><div class="muted">${esc(x.type||'Result')}</div></div></div>`).join(''))}}catch(_){} }
  init();
})();
