class SocialPost {
  final String id, authorId, body;
  final String? mediaUrl, replyToId, repostOfId, quoteOfId;
  final String mediaType, visibility, status;
  final int likeCount, commentCount, repostCount, viewCount;
  final DateTime createdAt;
  const SocialPost({required this.id,required this.authorId,required this.body,this.mediaUrl,this.replyToId,this.repostOfId,this.quoteOfId,this.mediaType='none',this.visibility='public',this.status='published',this.likeCount=0,this.commentCount=0,this.repostCount=0,this.viewCount=0,required this.createdAt});
  factory SocialPost.fromJson(Map<String,dynamic> j)=>SocialPost(id:j['id'] as String,authorId:j['author_id'] as String,body:j['body'] as String? ?? '',mediaUrl:j['media_url'] as String?,replyToId:j['reply_to_id'] as String?,repostOfId:j['repost_of_id'] as String?,quoteOfId:j['quote_of_id'] as String?,mediaType:j['media_type'] as String? ?? 'none',visibility:j['visibility'] as String? ?? 'public',status:j['status'] as String? ?? 'published',likeCount:(j['like_count'] as num?)?.toInt()??0,commentCount:(j['comment_count'] as num?)?.toInt()??0,repostCount:(j['repost_count'] as num?)?.toInt()??0,viewCount:(j['view_count'] as num?)?.toInt()??0,createdAt:DateTime.tryParse(j['created_at'] as String? ?? '')??DateTime.now());
}
class SocialComment { final String id,postId,authorId,body; final String? parentId; final int likeCount; final DateTime createdAt; const SocialComment({required this.id,required this.postId,required this.authorId,required this.body,this.parentId,this.likeCount=0,required this.createdAt}); factory SocialComment.fromJson(Map<String,dynamic> j)=>SocialComment(id:j['id'] as String,postId:j['post_id'] as String,authorId:j['author_id'] as String,body:j['body'] as String,parentId:j['parent_id'] as String?,likeCount:(j['like_count'] as num?)?.toInt()??0,createdAt:DateTime.tryParse(j['created_at'] as String? ?? '')??DateTime.now()); }
class SocialStory { final String id,authorId,mediaUrl,caption,mediaType,visibility; final DateTime expiresAt,createdAt; const SocialStory({required this.id,required this.authorId,required this.mediaUrl,this.caption='',this.mediaType='image',this.visibility='followers',required this.expiresAt,required this.createdAt}); factory SocialStory.fromJson(Map<String,dynamic> j)=>SocialStory(id:j['id'] as String,authorId:j['author_id'] as String,mediaUrl:j['media_url'] as String,caption:j['caption'] as String? ?? '',mediaType:j['media_type'] as String? ?? 'image',visibility:j['visibility'] as String? ?? 'followers',expiresAt:DateTime.parse(j['expires_at'] as String),createdAt:DateTime.parse(j['created_at'] as String)); }
class SocialReel { final String id,authorId,videoUrl,caption; final String? thumbnailUrl; final int durationMs,likeCount,commentCount,shareCount,viewCount,completionCount; final DateTime createdAt; const SocialReel({required this.id,required this.authorId,required this.videoUrl,this.caption='',this.thumbnailUrl,this.durationMs=0,this.likeCount=0,this.commentCount=0,this.shareCount=0,this.viewCount=0,this.completionCount=0,required this.createdAt}); factory SocialReel.fromJson(Map<String,dynamic> j)=>SocialReel(id:j['id'] as String,authorId:j['author_id'] as String,videoUrl:j['video_url'] as String,caption:j['caption'] as String? ?? '',thumbnailUrl:j['thumbnail_url'] as String?,durationMs:(j['duration_ms'] as num?)?.toInt()??0,likeCount:(j['like_count'] as num?)?.toInt()??0,commentCount:(j['comment_count'] as num?)?.toInt()??0,shareCount:(j['share_count'] as num?)?.toInt()??0,viewCount:(j['view_count'] as num?)?.toInt()??0,completionCount:(j['completion_count'] as num?)?.toInt()??0,createdAt:DateTime.tryParse(j['created_at'] as String? ?? '')??DateTime.now()); }
class CreatorMetric { final DateTime day; final int impressions,likes,comments,reposts,reelViews,reelCompletions,storyViews,followersGained,reports; const CreatorMetric({required this.day,this.impressions=0,this.likes=0,this.comments=0,this.reposts=0,this.reelViews=0,this.reelCompletions=0,this.storyViews=0,this.followersGained=0,this.reports=0}); factory CreatorMetric.fromJson(Map<String,dynamic> j)=>CreatorMetric(day:DateTime.parse(j['day'] as String),impressions:int.tryParse('${j['post_impressions']??0}')??0,likes:int.tryParse('${j['post_likes']??0}')??0,comments:int.tryParse('${j['post_comments']??0}')??0,reposts:int.tryParse('${j['post_reposts']??0}')??0,reelViews:int.tryParse('${j['reel_views']??0}')??0,reelCompletions:int.tryParse('${j['reel_completions']??0}')??0,storyViews:int.tryParse('${j['story_views']??0}')??0,followersGained:int.tryParse('${j['followers_gained']??0}')??0,reports:int.tryParse('${j['reports_received']??0}')??0); }
