const players=[
{name:'Brian O.',pos:'Winger',age:19,country:'Kenya',city:'Kisii',signal:92,club:'Grassroots Select',tags:['Explosive pace','1v1'],scout:'Scout signal: high'},
{name:'Amara D.',pos:'Striker',age:18,country:'Nigeria',city:'Lagos',signal:89,club:'City Academy',tags:['Finishing','Movement'],scout:'Scout signal: high'},
{name:'Ethan K.',pos:'Midfielder',age:20,country:'Ghana',city:'Kumasi',signal:86,club:'Asokwa FC',tags:['Passing','Vision'],scout:'Scout signal: rising'},
{name:'Musa J.',pos:'Defender',age:17,country:'Kenya',city:'Nakuru',signal:84,club:'Rift Valley XI',tags:['Tackling','Recovery'],scout:'Scout signal: rising'}];
const regions=[['🇰🇪','Kenya','1,240+ signals'],['🇳🇬','Nigeria','980+ signals'],['🇬🇭','Ghana','640+ signals'],['🇺🇬','Uganda','410+ signals'],['🇹🇿','Tanzania','390+ signals'],['🌍','Global','5,000+ signals']];
const scouts=[['SC','Licensed Scout','East Africa Talent Network'],['FC','Club Scout','Regional Academy Group'],['AR','Academy Recruiter','Grassroots Football Network']];
const feed=document.getElementById('feed'), toast=document.getElementById('toast');
function renderPlayers(list=players){feed.innerHTML=list.map((p,i)=>`<article class="talent"><div class="talent-top"><div class="player"><div class="avatar">${p.name[0]}</div><div><b>${p.name}</b><small>${p.city} · ${p.country}</small></div></div><div class="signal"><b>${p.signal}</b><small>DISCOVERY</small></div></div><div class="meta"><span class="tag">${p.pos}</span><span class="tag">U-${p.age<18?'18':'21'}</span><span class="tag">${p.club}</span>${p.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="actions"><button class="primary" onclick="toastMsg('Added ${p.name} to shortlist')">Shortlist</button><button onclick="toastMsg('Player profile opened')">View profile</button></div></article>`).join('')}
function renderRegions(){document.getElementById('regions').innerHTML=regions.map(r=>`<button class="region" onclick="filterRegion('${r[1]}')"><span>${r[0]}</span><strong>${r[1]}</strong><span>${r[2]}</span></button>`).join('')}
function renderScouts(){document.getElementById('scoutList').innerHTML=scouts.map(s=>`<div class="scout"><div class="avatar">${s[0]}</div><div><b>${s[1]}</b><small>${s[2]}</small></div><span class="verify">VERIFIED</span></div>`).join('')}
function filterRegion(country){document.querySelector('[data-tab="home"]').click();const list=players.filter(p=>p.country===country);renderPlayers(list.length?list:players);toastMsg(list.length?`${list.length} ${country} players shown`:`No local demo records for ${country} yet`)}
function toastMsg(m){toast.textContent=m;toast.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>toast.classList.remove('show'),1800)}
function switchTab(tab){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===tab));document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.tab===tab));window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav').forEach(n=>n.addEventListener('click',()=>switchTab(n.dataset.tab)));
document.querySelectorAll('.chip').forEach(c=>c.addEventListener('click',()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));c.classList.add('active');const f=c.dataset.filter;renderPlayers(f==='all'?players:players.filter(p=>f==='u21'?p.age<22:p.pos.toLowerCase().includes(f)));switchTab('home')}));
document.getElementById('query').addEventListener('input',e=>{const q=e.target.value.toLowerCase();renderPlayers(players.filter(p=>`${p.name} ${p.pos} ${p.country} ${p.city} ${p.club}`.toLowerCase().includes(q)))});
document.getElementById('submit').addEventListener('click',()=>{const n=document.getElementById('pName').value.trim();if(!n){toastMsg('Add the player name first');return}toastMsg(`${n} saved as a draft profile`);document.querySelectorAll('.form-card input,.form-card textarea').forEach(x=>x.value='')});
document.getElementById('searchBtn').addEventListener('click',()=>{switchTab('discover');document.getElementById('query').focus()});document.getElementById('bellBtn').addEventListener('click',()=>toastMsg('No new scout alerts'));
document.getElementById('seeAll').addEventListener('click',()=>switchTab('discover'));document.getElementById('locationBtn').addEventListener('click',()=>toastMsg('Location selector ready for country/region filters'));document.getElementById('profileAction').addEventListener('click',()=>toastMsg('Profile editor ready for the next backend pass'));
renderPlayers();renderRegions();renderScouts();
